# This workflow is for scanning this repo for malware
name: malware-scanner

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
    malware-security-scan:
    runs-on: ubuntu-latest
    name: Malware Scanner
    steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Malware Scanner
         uses: ./malware-scanner
         with:
             directories: .
             options: -rf
     